// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DepsService exposes dependency detection, installation and updates.
 * Install/update output is streamed to the frontend as "deps:log" events.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Check reports the current dependency state. Update checking is throttled
 * internally to once per day.
 */
export function Check(): $CancellablePromise<$models.DepsStatus> {
    return $Call.ByID(3952119168);
}

/**
 * Install installs a dependency: "yt-dlp", "ffmpeg" or "deno".
 */
export function Install(name: string): $CancellablePromise<void> {
    return $Call.ByID(405554539, name);
}

/**
 * Quit exits the application. Used when the user declines a mandatory
 * dependency install — the app cannot function without yt-dlp.
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(797236711);
}

/**
 * Update updates a dependency: "yt-dlp", "ffmpeg" or a JS runtime name
 * ("deno", "bun", "node").
 */
export function Update(name: string): $CancellablePromise<void> {
    return $Call.ByID(1591238361, name);
}
