// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DepsService from "./depsservice.js";
import * as Service from "./service.js";
export {
    DepsService,
    Service
};

export type {
    DepsStatus,
    Entry,
    State
} from "./models.js";
