// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as deps$0 from "../deps/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as download$0 from "../download/models.js";

/**
 * DepsStatus is the startup dependency report the frontend acts on: missing
 * installs, runtime upgrades, and pending yt-dlp updates.
 */
export interface DepsStatus {
    "ytDlpInstalled": boolean;
    "ffmpegInstalled": boolean;
    "runtime": string;
    "runtimeFound": boolean;
    "runtimeRecommended": boolean;
    "update"?: deps$0.UpdateInfo | null;
    "updateAvailable": boolean;
}

/**
 * Entry is the JSON view of a queue entry sent to the frontend.
 */
export interface Entry {
    "id": number;
    "url": string;
    "title": string;
    "status": string;
    "progress": number;
    "error"?: string;
    "playlist"?: download$0.PlaylistMeta | null;
    "outputPath"?: string;
}

/**
 * State is the full snapshot emitted to the frontend on every change.
 */
export interface State {
    "entries": Entry[] | null;
    "resolving": number;
    "isRunning": boolean;
    "config": config$0.Config;
    "runtime": string;
}
