// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service owns the queue and drives downloads. It is the sole source of
 * "state" events; the frontend never mutates state directly, it only calls
 * these methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddURL resolves a URL (single video or playlist) and adds the results to
 * the queue. Mirrors the TUI flow: increment "resolving", resolve in the
 * background, then either add playlist items, add the single video, or add a
 * failed entry carrying the resolve error.
 */
export function AddURL(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(616106746, rawURL);
}

/**
 * ClearAll empties the queue, including history (TUI's ctrl+r).
 */
export function ClearAll(): $CancellablePromise<void> {
    return $Call.ByID(779887774);
}

/**
 * GetState returns the current snapshot without emitting an event.
 */
export function GetState(): $CancellablePromise<$models.State> {
    return $Call.ByID(2538971395);
}

/**
 * RemoveBatch removes every entry of a playlist batch.
 */
export function RemoveBatch(batchID: string): $CancellablePromise<void> {
    return $Call.ByID(3149104546, batchID);
}

/**
 * RemoveEntry removes a single entry by ID.
 */
export function RemoveEntry(id: number): $CancellablePromise<void> {
    return $Call.ByID(2316823502, id);
}

/**
 * RemoveLast removes the most recently queued entry (TUI's backspace action).
 */
export function RemoveLast(): $CancellablePromise<void> {
    return $Call.ByID(3226352378);
}

/**
 * Start begins downloading the queue sequentially, one entry at a time.
 * Returns false if a run is already in progress, URLs are still resolving,
 * or the queue is empty — mirroring the TUI's tryStartDownloads.
 */
export function Start(): $CancellablePromise<boolean> {
    return $Call.ByID(3558839338);
}
