// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AudioQuality is either a VBR integer (0–10, as string) or a CBR bitrate like "192K".
 */
export type AudioQuality = string;

/**
 * Config is the global configuration, mirroring the TypeScript ConfigSchema.
 */
export interface Config {
    "Kind": OutputKind;
    "Format": string;
    "AudioQuality": AudioQuality;
    "VideoQuality": string;
    "OutputFolder": string;
}

/**
 * OutputKind mirrors the TypeScript OutputKindSchema.
 */
export enum OutputKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindAudio = "audio",
    KindVideo = "video",
    KindAuto = "auto",
};
