// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlaylistMeta is set on entries that were expanded from a playlist.
 */
export interface PlaylistMeta {
    /**
     * Unique ID for this specific addition
     */
    "BatchID": string;
    "PlaylistTitle": string;

    /**
     * 1-based position within the playlist
     */
    "Index": number;

    /**
     * total number of items in the playlist
     */
    "Total": number;
}
