// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AreDependenciesReady():Promise<boolean>;

export function Download(arg1:main.VideoRequest):Promise<string>;
