// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AreDependenciesReady() {
  return window['go']['main']['App']['AreDependenciesReady']();
}

export function Download(arg1) {
  return window['go']['main']['App']['Download'](arg1);
}
